version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: whatsapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: python3 -m app.workers.send_worker

  failed_worker:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: python3 -m app.workers.failed_worker


volumes:
  pgdata:
  redisdata:
